version: '3.4'
services:
  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - 8080:8080
    volumes:
      - './etc:/etc/trino'
      - '/data/files:/data/files'
      - '/data/trino:/var/trino/data'
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001" --address ":9000"
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio1234
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data      
